### ISSUE TITLE
Telegram Auction Bot

### ISSUE THREAD

**Issue by 128-95** [kittycash/telegram-butler#1]
Create a telgram auction Bot that performs the following tasks:

Tells people who newly join the group to read the pinned message

Gives updates for people on the remaining time left for the auction.
--> with decreasing time to the end of auction more frequent announcements
--> counts down from 100 to 0 in an interval of 1 sec
--> from 10 to 0, every new bid is starting the 10 to 0 timer again.

announce the winner and bid that finally won and ask them to PM me (@erichkaestner)

(Moving this here from https://github.com/kittycash/teller/issues/6)

**Comment by 128-95** [comment]
Deletion of welcome message after 90 seconds is fine.

**Comment by therealssj** [comment]
Do you guys want an `event` scheduling functionality so that the bot can start an auction. 
You can write a telegram msg and have the bot forward it(will look as if the bot sent it) to the group at a later time if required.

**Comment by 128-95** [comment]
Might be interesting, but not priority.

**Comment by jdknives** [comment]
How is that bot going? @therealssj @128-95

**Comment by jdknives** [comment]
Updates? @therealssj
